package aii.steps;

import org.junit.Test;

import aii.utils.APIConstants;
import aii.utils.APIGlobalVariables;
import io.cucumber.java.en.When;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;

public class APIModelRegression {

//Validation of User Story-5965
@Test	
@When("I enter required body information for required scenarios and I validate response body status code is ok")
public void i_enter_required_body_information_for_required_scenarios_and_i_validate_response_body_status_code_is_ok() {
    
	//Scenario 1-1
	
	String payload1="{\r\n"
			+ "  \"customerId\": \"AI\",\r\n"
			+ "  \r\n"
			+ "  \"customerKey\": null,\r\n"
			+ "  \"quoteRequest\": {\r\n"
			+ "  \"productType\": \"DP3\",\r\n"
			+ "  \"producer\": \"AG6718A1\",\r\n"
			+ "  \"priorPolicy\": {\r\n"
			+ "    \"expirationDate\": \"2022-02-01\",\r\n"
			+ "    \"premium\": 1200,\r\n"
			+ "    \"carrier\": \"OTHER\",\r\n"
			+ "    \"originalEffectiveDate\": \"\",\r\n"
			+ "    \"priorPolicyNumber\": \"\"\r\n"
			+ "  },\r\n"
			+ "  \"entityType\": \"JOINT\",\r\n"
			+ "  \"insured\": {\r\n"
			+ "    \"name\": {\r\n"
			+ "      \"commercial\": \"Victor Hedman and Sanna Hedman\",\r\n"
			+ "      \"first\": \"Victor\",\r\n"
			+ "      \"middle\": \"\",\r\n"
			+ "      \"last\": \"Hedman\"\r\n"
			+ "    },\r\n"
			+ "    \"dateOfBirth\": \"1990-12-18\",\r\n"
			+ "    \"primaryPhone\": {\r\n"
			+ "      \"value\": \"(904)371-4627\",\r\n"
			+ "      \"name\": \"Victor Hedman\"\r\n"
			+ "    },\r\n"
			+ "    \"email\": \"\"\r\n"
			+ "  },\r\n"
			+ "  \"insuranceScore\": \"\",\r\n"
			+ "  \"coInsured\": {\r\n"
			+ "    \"firstName\": \"Sanna\",\r\n"
			+ "    \"middleName\": \"\",\r\n"
			+ "    \"lastName\": \"Hedman\",\r\n"
			+ "    \"dateOfBirth\": \"1991-09-06\"\r\n"
			+ "  },\r\n"
			+ "  \"insuredProperty\": {\r\n"
			+ "    \"dwellingType\": \"SINGLE FAMILY\",\r\n"
			+ "      \"location\": {\r\n"
			+ "      \"address\": \"1710 E Kirby\",\r\n"
			+ "      \"city\": \"TAMPA\",\r\n"
			+ "      \"county\": \"Hillsborough\",\r\n"
			+ "      \"state\": \"FL\",\r\n"
			+ "      \"zipCode\": \"33604\"\r\n"
			+ "    },\r\n"
			+ "    \"bceg\": \"UNGRADED\",\r\n"
			+ "    \"constructionType\": \"FRAME\",\r\n"
			+ "    \"numberOfUnits\": 1,\r\n"
			+ "    \"occupancy\": \"OWNER\",\r\n"
			+ "    \"monthsOccupied\": 12,\r\n"
			+ "    \"numberOfStories\": 1,\r\n"
			+ "    \"storyUnitIsLocated\": 0,\r\n"
			+ "    \"distanceToCoast\": \"15 mi to less than 20 mi\"\r\n"
			+ "  },\r\n"
			+ "  \"dwelling\": {\r\n"
			+ "    \"distanceToHydrant\": \"LESS THAN OR EQUAL 1000 FEET\",\r\n"
			+ "    \"protectionClass\": 3,\r\n"
			+ "    \"squareFeet\": 1068,\r\n"
			+ "    \"yearOfConstruction\": 2018,\r\n"
			+ "    \"yearRoofMaterialUpdated\": 2018,\r\n"
			+ "    \"propertyManaged\": false,\r\n"
			+ "    \"shortTermRental\": false,\r\n"
			+ "    \"roofMaterial\": \"Concrete/Clay Tile\"\r\n"
			+ "  },\r\n"
			+ "  \"reservePackage\": \"BASIC\",\r\n"
			+ "  \"deductibles\": {\r\n"
			+ "    \"aop\": 1000,\r\n"
			+ "    \"hurricane\": 10,\r\n"
			+ "    \"windHail\": 1000,\r\n"
			+ "    \"windHailExclusion\": false\r\n"
			+ "  },\r\n"
			+ "  \"coverages\": {\r\n"
			+ "    \"covA\": 350000,\r\n"
			+ "    \"covB\": 2,\r\n"
			+ "    \"covC\": 100000,\r\n"
			+ "    \"covE\": 100000,\r\n"
			+ "    \"covF\": 5000,\r\n"
			+ "    \"covL\": 0,\r\n"
			+ "    \"covM\": 0,\r\n"
			+ "    \"homeComputer\": 2500,\r\n"
			+ "    \"homeSystemsProtection\": \"50000/10000\",\r\n"
			+ "    \"identityRecovery\": \"15000\",\r\n"
			+ "    \"fungiMoldEtc\": \"10000/10000\",\r\n"
			+ "    \"ordinanceOrLaw\": 0,\r\n"
			+ "    \"serviceLine\": \"None\",\r\n"
			+ "    \"waterBackupSumpOverflow\": \"\",\r\n"
			+ "    \"refrigeratedPersonalProperty\": false\r\n"
			+ "  },\r\n"
			+ "  \"optionalCoverages\": {\r\n"
			+ "    \"animalLiability\": true,\r\n"
			+ "    \"animalLiabilityAmount\": 0,\r\n"
			+ "    \"carportPoolCageScreen\": \"\",\r\n"
			+ "    \"increasedDwellingReplacementCost\": true,\r\n"
			+ "    \"limitedTheft\": false,\r\n"
			+ "    \"personalInjury\": false,\r\n"
			+ "    \"personalPropertyReplacementCost\": false,\r\n"
			+ "    \"sinkholeLoss\": \"10\",\r\n"
			+ "    \"waterDamageExclusion\": false,\r\n"
			+ "    \"waterDamageLimited\": false,\r\n"
			+ "    \"unitOwnersCovA\": false,\r\n"
			+ "    \"unitOwnersCovC\": false,\r\n"
			+ "    \"storageSlipRental\": false\r\n"
			+ "  },\r\n"
			+ "  \"discounts\": {\r\n"
			+ "    \"burglarAlarmCredit\": \"CENTRAL STATION\",\r\n"
			+ "    \"fireAlarmCredit\": \"CENTRAL STATION\",\r\n"
			+ "    \"proofOfUpdates\": \"ROOF ONLY\",\r\n"
			+ "    \"securedCommunityBldg\": \"\",\r\n"
			+ "    \"sprinklerSystem\": \"NONE\",\r\n"
			+ "    \"openFoundation\": false,\r\n"
			+ "    \"hardiplankSiding\": false,\r\n"
			+ "    \"military\": true\r\n"
			+ "  },\r\n"
			+ "  \"windMitigation\": {\r\n"
			+ "    \"openingProtection\": \"NONE\",\r\n"
			+ "    \"roofCover\": \"FBC EQUIVALENT\",\r\n"
			+ "    \"roofDeck\": \"\",\r\n"
			+ "    \"roofDeckAttachment\": \"\",\r\n"
			+ "    \"roofShape\": \"GABLE\",\r\n"
			+ "    \"roofToWallAttachment\": \"\",\r\n"
			+ "    \"secondaryWaterResistance\": false\r\n"
			+ "  },\r\n"
			+ "  \"effectiveDate\": \"2022-02-01\",\r\n"
			+ "   \"dataReports\": {\r\n"
			+ "  	\"runInsuranceScore\": false\r\n"
			+ "  }	\r\n"
			+ "} ,\r\n"
			+ "  \"requestId\": \"8720-88776\",\r\n"
			+ "  \"responseDetail\": true\r\n"
			+ "}";
	
		RestAssured.baseURI=APIConstants.BASE_URI;
		
		RestAssured.given().auth().preemptive().
		basic(APIGlobalVariables.harvUsername, APIGlobalVariables.harvPassword).
		body(payload1)
		.contentType(ContentType.JSON).post().prettyPeek().then().
		assertThat().statusCode(200);

		//Scenario 1-2
		
		String payload2="{\r\n"
				+ "  \"customerId\": \"AI\",\r\n"
				+ "  \r\n"
				+ "  \"customerKey\": null,\r\n"
				+ "  \"quoteRequest\": {\r\n"
				+ "  \"productType\": \"DP3\",\r\n"
				+ "  \"producer\": \"AG6718A1\",\r\n"
				+ "  \"priorPolicy\": {\r\n"
				+ "    \"expirationDate\": \"2022-02-01\",\r\n"
				+ "    \"premium\": 1200,\r\n"
				+ "    \"carrier\": \"OTHER\",\r\n"
				+ "    \"originalEffectiveDate\": \"\",\r\n"
				+ "    \"priorPolicyNumber\": \"\"\r\n"
				+ "  },\r\n"
				+ "  \"entityType\": \"JOINT\",\r\n"
				+ "  \"insured\": {\r\n"
				+ "    \"name\": {\r\n"
				+ "      \"commercial\": \"Victor Hedman and Sanna Hedman\",\r\n"
				+ "      \"first\": \"Victor\",\r\n"
				+ "      \"middle\": \"\",\r\n"
				+ "      \"last\": \"Hedman\"\r\n"
				+ "    },\r\n"
				+ "    \"dateOfBirth\": \"1990-12-18\",\r\n"
				+ "    \"primaryPhone\": {\r\n"
				+ "      \"value\": \"(904)371-4627\",\r\n"
				+ "      \"name\": \"Victor Hedman\"\r\n"
				+ "    },\r\n"
				+ "    \"email\": \"\"\r\n"
				+ "  },\r\n"
				+ "  \"insuranceScore\": \"\",\r\n"
				+ "  \"coInsured\": {\r\n"
				+ "    \"firstName\": \"Sanna\",\r\n"
				+ "    \"middleName\": \"\",\r\n"
				+ "    \"lastName\": \"Hedman\",\r\n"
				+ "    \"dateOfBirth\": \"1991-09-06\"\r\n"
				+ "  },\r\n"
				+ "  \"insuredProperty\": {\r\n"
				+ "    \"dwellingType\": \"SINGLE FAMILY\",\r\n"
				+ "      \"location\": {\r\n"
				+ "      \"address\": \"1710 E Kirby\",\r\n"
				+ "      \"city\": \"TAMPA\",\r\n"
				+ "      \"county\": \"Hillsborough\",\r\n"
				+ "      \"state\": \"FL\",\r\n"
				+ "      \"zipCode\": \"33604\"\r\n"
				+ "    },\r\n"
				+ "    \"bceg\": \"UNGRADED\",\r\n"
				+ "    \"constructionType\": \"FRAME\",\r\n"
				+ "    \"numberOfUnits\": 1,\r\n"
				+ "    \"occupancy\": \"OWNER\",\r\n"
				+ "    \"monthsOccupied\": 12,\r\n"
				+ "    \"numberOfStories\": 1,\r\n"
				+ "    \"storyUnitIsLocated\": 0,\r\n"
				+ "    \"distanceToCoast\": \"15 mi to less than 20 mi\"\r\n"
				+ "  },\r\n"
				+ "  \"dwelling\": {\r\n"
				+ "    \"distanceToHydrant\": \"LESS THAN OR EQUAL 1000 FEET\",\r\n"
				+ "    \"protectionClass\": 3,\r\n"
				+ "    \"squareFeet\": 1068,\r\n"
				+ "    \"yearOfConstruction\": 2018,\r\n"
				+ "    \"yearRoofMaterialUpdated\": 2018,\r\n"
				+ "    \"propertyManaged\": false,\r\n"
				+ "    \"shortTermRental\": false,\r\n"
				+ "    \"roofMaterial\": \"Concrete/Clay Tile\"\r\n"
				+ "  },\r\n"
				+ "  \"reservePackage\": \"INTEGRITYSELECT\",\r\n"
				+ "  \"deductibles\": {\r\n"
				+ "    \"aop\": 1000,\r\n"
				+ "    \"hurricane\": 10,\r\n"
				+ "    \"windHail\": 1000,\r\n"
				+ "    \"windHailExclusion\": false\r\n"
				+ "  },\r\n"
				+ "  \"coverages\": {\r\n"
				+ "    \"covA\": 350000,\r\n"
				+ "    \"covB\": 2,\r\n"
				+ "    \"covC\": 100000,\r\n"
				+ "    \"covE\": 100000,\r\n"
				+ "    \"covF\": 5000,\r\n"
				+ "    \"covL\": 0,\r\n"
				+ "    \"covM\": 0,\r\n"
				+ "    \"homeComputer\": 2500,\r\n"
				+ "    \"homeSystemsProtection\": \"50000/10000\",\r\n"
				+ "    \"identityRecovery\": \"15000\",\r\n"
				+ "    \"fungiMoldEtc\": \"10000/10000\",\r\n"
				+ "    \"ordinanceOrLaw\": 0,\r\n"
				+ "    \"serviceLine\": \"None\",\r\n"
				+ "    \"waterBackupSumpOverflow\": \"\",\r\n"
				+ "    \"refrigeratedPersonalProperty\": false\r\n"
				+ "  },\r\n"
				+ "  \"optionalCoverages\": {\r\n"
				+ "    \"animalLiability\": true,\r\n"
				+ "    \"animalLiabilityAmount\": 0,\r\n"
				+ "    \"carportPoolCageScreen\": \"\",\r\n"
				+ "    \"increasedDwellingReplacementCost\": true,\r\n"
				+ "    \"limitedTheft\": false,\r\n"
				+ "    \"personalInjury\": false,\r\n"
				+ "    \"personalPropertyReplacementCost\": false,\r\n"
				+ "    \"sinkholeLoss\": \"10\",\r\n"
				+ "    \"waterDamageExclusion\": false,\r\n"
				+ "    \"waterDamageLimited\": false,\r\n"
				+ "    \"unitOwnersCovA\": false,\r\n"
				+ "    \"unitOwnersCovC\": false,\r\n"
				+ "    \"storageSlipRental\": false\r\n"
				+ "  },\r\n"
				+ "  \"discounts\": {\r\n"
				+ "    \"burglarAlarmCredit\": \"CENTRAL STATION\",\r\n"
				+ "    \"fireAlarmCredit\": \"CENTRAL STATION\",\r\n"
				+ "    \"proofOfUpdates\": \"ROOF ONLY\",\r\n"
				+ "    \"securedCommunityBldg\": \"\",\r\n"
				+ "    \"sprinklerSystem\": \"NONE\",\r\n"
				+ "    \"openFoundation\": false,\r\n"
				+ "    \"hardiplankSiding\": false,\r\n"
				+ "    \"military\": true\r\n"
				+ "  },\r\n"
				+ "  \"windMitigation\": {\r\n"
				+ "    \"openingProtection\": \"NONE\",\r\n"
				+ "    \"roofCover\": \"FBC EQUIVALENT\",\r\n"
				+ "    \"roofDeck\": \"\",\r\n"
				+ "    \"roofDeckAttachment\": \"\",\r\n"
				+ "    \"roofShape\": \"GABLE\",\r\n"
				+ "    \"roofToWallAttachment\": \"\",\r\n"
				+ "    \"secondaryWaterResistance\": false\r\n"
				+ "  },\r\n"
				+ "  \"effectiveDate\": \"2022-02-01\",\r\n"
				+ "   \"dataReports\": {\r\n"
				+ "  	\"runInsuranceScore\": false\r\n"
				+ "  }	\r\n"
				+ "} ,\r\n"
				+ "  \"requestId\": \"8720-88776\",\r\n"
				+ "  \"responseDetail\": true\r\n"
				+ "}";
		
		RestAssured.baseURI=APIConstants.BASE_URI;
		
		RestAssured.given().auth().preemptive().
		basic(APIGlobalVariables.harvUsername, APIGlobalVariables.harvPassword).
		body(payload2)
		.contentType(ContentType.JSON).post().prettyPeek().then().
		assertThat().statusCode(200);
		
		
		//Scenario 2
		String payload3="{\r\n"
				+ "  \"customerId\": \"AI\",\r\n"
				+ "  \r\n"
				+ "  \"customerKey\": null,\r\n"
				+ "  \"quoteRequest\": {\r\n"
				+ "  \"productType\": \"DP3\",\r\n"
				+ "  \"producer\": \"AG6718A1\",\r\n"
				+ "  \"priorPolicy\": {\r\n"
				+ "    \"expirationDate\": \"2022-02-01\",\r\n"
				+ "    \"premium\": 1200,\r\n"
				+ "    \"carrier\": \"OTHER\",\r\n"
				+ "    \"originalEffectiveDate\": \"\",\r\n"
				+ "    \"priorPolicyNumber\": \"\"\r\n"
				+ "  },\r\n"
				+ "  \"entityType\": \"JOINT\",\r\n"
				+ "  \"insured\": {\r\n"
				+ "    \"name\": {\r\n"
				+ "      \"commercial\": \"Victor Hedman and Sanna Hedman\",\r\n"
				+ "      \"first\": \"Victor\",\r\n"
				+ "      \"middle\": \"\",\r\n"
				+ "      \"last\": \"Hedman\"\r\n"
				+ "    },\r\n"
				+ "    \"dateOfBirth\": \"1990-12-18\",\r\n"
				+ "    \"primaryPhone\": {\r\n"
				+ "      \"value\": \"(904)371-4627\",\r\n"
				+ "      \"name\": \"Victor Hedman\"\r\n"
				+ "    },\r\n"
				+ "    \"email\": \"\"\r\n"
				+ "  },\r\n"
				+ "  \"insuranceScore\": \"\",\r\n"
				+ "  \"coInsured\": {\r\n"
				+ "    \"firstName\": \"Sanna\",\r\n"
				+ "    \"middleName\": \"\",\r\n"
				+ "    \"lastName\": \"Hedman\",\r\n"
				+ "    \"dateOfBirth\": \"1991-09-06\"\r\n"
				+ "  },\r\n"
				+ "  \"insuredProperty\": {\r\n"
				+ "    \"dwellingType\": \"SINGLE FAMILY\",\r\n"
				+ "      \"location\": {\r\n"
				+ "      \"address\": \"1710 E Kirby\",\r\n"
				+ "      \"city\": \"TAMPA\",\r\n"
				+ "      \"county\": \"Hillsborough\",\r\n"
				+ "      \"state\": \"FL\",\r\n"
				+ "      \"zipCode\": \"33604\"\r\n"
				+ "    },\r\n"
				+ "    \"bceg\": \"UNGRADED\",\r\n"
				+ "    \"constructionType\": \"FRAME\",\r\n"
				+ "    \"numberOfUnits\": 1,\r\n"
				+ "    \"occupancy\": \"TENANT\",\r\n"
				+ "    \"monthsOccupied\": 12,\r\n"
				+ "    \"numberOfStories\": 1,\r\n"
				+ "    \"storyUnitIsLocated\": 0,\r\n"
				+ "    \"distanceToCoast\": \"15 mi to less than 20 mi\"\r\n"
				+ "  },\r\n"
				+ "  \"dwelling\": {\r\n"
				+ "    \"distanceToHydrant\": \"LESS THAN OR EQUAL 1000 FEET\",\r\n"
				+ "    \"protectionClass\": 3,\r\n"
				+ "    \"squareFeet\": 1068,\r\n"
				+ "    \"yearOfConstruction\": 2018,\r\n"
				+ "    \"yearRoofMaterialUpdated\": 2018,\r\n"
				+ "    \"propertyManaged\": false,\r\n"
				+ "    \"shortTermRental\": false,\r\n"
				+ "    \"roofMaterial\": \"Concrete/Clay Tile\"\r\n"
				+ "  },\r\n"
				+ "  \"reservePackage\": \"BASIC\",\r\n"
				+ "  \"deductibles\": {\r\n"
				+ "    \"aop\": 1000,\r\n"
				+ "    \"hurricane\": 10,\r\n"
				+ "    \"windHail\": 1000,\r\n"
				+ "    \"windHailExclusion\": false\r\n"
				+ "  },\r\n"
				+ "  \"coverages\": {\r\n"
				+ "    \"covA\": 350000,\r\n"
				+ "    \"covB\": 2,\r\n"
				+ "    \"covC\": 0,\r\n"
				+ "    \"covE\": 100000,\r\n"
				+ "    \"covF\": 5000,\r\n"
				+ "    \"covL\": 0,\r\n"
				+ "    \"covM\": 0,\r\n"
				+ "    \"homeComputer\": 2500,\r\n"
				+ "    \"homeSystemsProtection\": \"50000/10000\",\r\n"
				+ "    \"identityRecovery\": \"15000\",\r\n"
				+ "    \"fungiMoldEtc\": \"10000/10000\",\r\n"
				+ "    \"ordinanceOrLaw\": 0,\r\n"
				+ "    \"serviceLine\": \"None\",\r\n"
				+ "    \"waterBackupSumpOverflow\": \"\",\r\n"
				+ "    \"refrigeratedPersonalProperty\": false\r\n"
				+ "  },\r\n"
				+ "  \"optionalCoverages\": {\r\n"
				+ "    \"animalLiability\": true,\r\n"
				+ "    \"animalLiabilityAmount\": 0,\r\n"
				+ "    \"carportPoolCageScreen\": \"\",\r\n"
				+ "    \"increasedDwellingReplacementCost\": true,\r\n"
				+ "    \"limitedTheft\": false,\r\n"
				+ "    \"personalInjury\": false,\r\n"
				+ "    \"personalPropertyReplacementCost\": false,\r\n"
				+ "    \"sinkholeLoss\": \"10\",\r\n"
				+ "    \"waterDamageExclusion\": false,\r\n"
				+ "    \"waterDamageLimited\": false,\r\n"
				+ "    \"unitOwnersCovA\": false,\r\n"
				+ "    \"unitOwnersCovC\": false,\r\n"
				+ "    \"storageSlipRental\": false\r\n"
				+ "  },\r\n"
				+ "  \"discounts\": {\r\n"
				+ "    \"burglarAlarmCredit\": \"CENTRAL STATION\",\r\n"
				+ "    \"fireAlarmCredit\": \"CENTRAL STATION\",\r\n"
				+ "    \"proofOfUpdates\": \"ROOF ONLY\",\r\n"
				+ "    \"securedCommunityBldg\": \"\",\r\n"
				+ "    \"sprinklerSystem\": \"NONE\",\r\n"
				+ "    \"openFoundation\": false,\r\n"
				+ "    \"hardiplankSiding\": false,\r\n"
				+ "    \"military\": true\r\n"
				+ "  },\r\n"
				+ "  \"windMitigation\": {\r\n"
				+ "    \"openingProtection\": \"NONE\",\r\n"
				+ "    \"roofCover\": \"FBC EQUIVALENT\",\r\n"
				+ "    \"roofDeck\": \"\",\r\n"
				+ "    \"roofDeckAttachment\": \"\",\r\n"
				+ "    \"roofShape\": \"GABLE\",\r\n"
				+ "    \"roofToWallAttachment\": \"\",\r\n"
				+ "    \"secondaryWaterResistance\": false\r\n"
				+ "  },\r\n"
				+ "  \"effectiveDate\": \"2022-02-01\",\r\n"
				+ "   \"dataReports\": {\r\n"
				+ "  	\"runInsuranceScore\": false\r\n"
				+ "  }	\r\n"
				+ "} ,\r\n"
				+ "  \"requestId\": \"8720-88776\",\r\n"
				+ "  \"responseDetail\": true\r\n"
				+ "}";
		
		RestAssured.baseURI=APIConstants.BASE_URI;
		
		RestAssured.given().auth().preemptive().
		basic(APIGlobalVariables.harvUsername, APIGlobalVariables.harvPassword).
		body(payload3)
		.contentType(ContentType.JSON).post().prettyPeek().then().
		assertThat().statusCode(200);
		
		
		//Scenario 3
		String payload4="{\r\n"
				+ "  \"customerId\": \"AI\",\r\n"
				+ "  \r\n"
				+ "  \"customerKey\": null,\r\n"
				+ "  \"quoteRequest\": {\r\n"
				+ "  \"productType\": \"DP3\",\r\n"
				+ "  \"producer\": \"AG6718A1\",\r\n"
				+ "  \"priorPolicy\": {\r\n"
				+ "    \"expirationDate\": \"2022-02-01\",\r\n"
				+ "    \"premium\": 1200,\r\n"
				+ "    \"carrier\": \"OTHER\",\r\n"
				+ "    \"originalEffectiveDate\": \"\",\r\n"
				+ "    \"priorPolicyNumber\": \"\"\r\n"
				+ "  },\r\n"
				+ "  \"entityType\": \"JOINT\",\r\n"
				+ "  \"insured\": {\r\n"
				+ "    \"name\": {\r\n"
				+ "      \"commercial\": \"Victor Hedman and Sanna Hedman\",\r\n"
				+ "      \"first\": \"Victor\",\r\n"
				+ "      \"middle\": \"\",\r\n"
				+ "      \"last\": \"Hedman\"\r\n"
				+ "    },\r\n"
				+ "    \"dateOfBirth\": \"1990-12-18\",\r\n"
				+ "    \"primaryPhone\": {\r\n"
				+ "      \"value\": \"(904)371-4627\",\r\n"
				+ "      \"name\": \"Victor Hedman\"\r\n"
				+ "    },\r\n"
				+ "    \"email\": \"\"\r\n"
				+ "  },\r\n"
				+ "  \"insuranceScore\": \"Better Than Average (750-849)\",\r\n"
				+ "  \"coInsured\": {\r\n"
				+ "    \"firstName\": \"Sanna\",\r\n"
				+ "    \"middleName\": \"\",\r\n"
				+ "    \"lastName\": \"Hedman\",\r\n"
				+ "    \"dateOfBirth\": \"1991-09-06\"\r\n"
				+ "  },\r\n"
				+ "  \"insuredProperty\": {\r\n"
				+ "    \"dwellingType\": \"SINGLE FAMILY\",\r\n"
				+ "      \"location\": {\r\n"
				+ "      \"address\": \"1710 E Kirby\",\r\n"
				+ "      \"city\": \"TAMPA\",\r\n"
				+ "      \"county\": \"Hillsborough\",\r\n"
				+ "      \"state\": \"FL\",\r\n"
				+ "      \"zipCode\": \"33604\"\r\n"
				+ "    },\r\n"
				+ "    \"bceg\": \"UNGRADED\",\r\n"
				+ "    \"constructionType\": \"FRAME\",\r\n"
				+ "    \"numberOfUnits\": 1,\r\n"
				+ "    \"occupancy\": \"OWNER\",\r\n"
				+ "    \"monthsOccupied\": 12,\r\n"
				+ "    \"numberOfStories\": 1,\r\n"
				+ "    \"storyUnitIsLocated\": 0,\r\n"
				+ "    \"distanceToCoast\": \"15 mi to less than 20 mi\"\r\n"
				+ "  },\r\n"
				+ "  \"dwelling\": {\r\n"
				+ "    \"distanceToHydrant\": \"LESS THAN OR EQUAL 1000 FEET\",\r\n"
				+ "    \"protectionClass\": 3,\r\n"
				+ "    \"squareFeet\": 1068,\r\n"
				+ "    \"yearOfConstruction\": 2018,\r\n"
				+ "    \"yearRoofMaterialUpdated\": 2018,\r\n"
				+ "    \"propertyManaged\": false,\r\n"
				+ "    \"shortTermRental\": false,\r\n"
				+ "    \"roofMaterial\": \"Concrete/Clay Tile\"\r\n"
				+ "  },\r\n"
				+ "  \"reservePackage\": \"INTEGRITYSELECT\",\r\n"
				+ "  \"deductibles\": {\r\n"
				+ "    \"aop\": 1000,\r\n"
				+ "    \"hurricane\": 10,\r\n"
				+ "    \"windHail\": 1000,\r\n"
				+ "    \"windHailExclusion\": false\r\n"
				+ "  },\r\n"
				+ "  \"coverages\": {\r\n"
				+ "    \"covA\": 550000,\r\n"
				+ "    \"covB\": 2,\r\n"
				+ "    \"covC\": 130000,\r\n"
				+ "    \"covE\": 100000,\r\n"
				+ "    \"covF\": 5000,\r\n"
				+ "    \"covL\": 0,\r\n"
				+ "    \"covM\": 0,\r\n"
				+ "    \"homeComputer\": 2500,\r\n"
				+ "    \"homeSystemsProtection\": \"50000/10000\",\r\n"
				+ "    \"identityRecovery\": \"15000\",\r\n"
				+ "    \"lossAssessment\": 0,\r\n"
				+ "    \"fungiMoldEtc\": \"10000/10000\",\r\n"
				+ "    \"ordinanceOrLaw\": 0,\r\n"
				+ "    \"serviceLine\": \"None\",\r\n"
				+ "    \"waterBackupSumpOverflow\": \"\",\r\n"
				+ "    \"refrigeratedPersonalProperty\": false\r\n"
				+ "  },\r\n"
				+ "  \"optionalCoverages\": {\r\n"
				+ "    \"animalLiability\": true,\r\n"
				+ "    \"animalLiabilityAmount\": 0,\r\n"
				+ "    \"carportPoolCageScreen\": \"\",\r\n"
				+ "    \"increasedDwellingReplacementCost\": true,\r\n"
				+ "    \"limitedTheft\": false,\r\n"
				+ "    \"personalInjury\": false,\r\n"
				+ "    \"personalPropertyReplacementCost\": false,\r\n"
				+ "    \"sinkholeLoss\": \"10\",\r\n"
				+ "    \"waterDamageExclusion\": false,\r\n"
				+ "    \"waterDamageLimited\": false,\r\n"
				+ "    \"unitOwnersCovA\": false,\r\n"
				+ "    \"unitOwnersCovC\": false,\r\n"
				+ "    \"storageSlipRental\": false\r\n"
				+ "  },\r\n"
				+ "  \"discounts\": {\r\n"
				+ "    \"burglarAlarmCredit\": \"CENTRAL STATION\",\r\n"
				+ "    \"fireAlarmCredit\": \"CENTRAL STATION\",\r\n"
				+ "    \"proofOfUpdates\": \"ROOF ONLY\",\r\n"
				+ "    \"securedCommunityBldg\": \"\",\r\n"
				+ "    \"sprinklerSystem\": \"NONE\",\r\n"
				+ "    \"openFoundation\": false,\r\n"
				+ "    \"hardiplankSiding\": false,\r\n"
				+ "    \"military\": true\r\n"
				+ "  },\r\n"
				+ "  \"windMitigation\": {\r\n"
				+ "    \"openingProtection\": \"NONE\",\r\n"
				+ "    \"roofCover\": \"FBC EQUIVALENT\",\r\n"
				+ "    \"roofDeck\": \"\",\r\n"
				+ "    \"roofDeckAttachment\": \"\",\r\n"
				+ "    \"roofShape\": \"GABLE\",\r\n"
				+ "    \"roofToWallAttachment\": \"\",\r\n"
				+ "    \"secondaryWaterResistance\": false\r\n"
				+ "  },\r\n"
				+ "  \"effectiveDate\": \"2022-02-01\",\r\n"
				+ "   \"dataReports\": {\r\n"
				+ "  	\"runInsuranceScore\": false\r\n"
				+ "  }	\r\n"
				+ "} ,\r\n"
				+ "  \"requestId\": \"8720-88776\",\r\n"
				+ "  \"responseDetail\": true\r\n"
				+ "}";
		
		RestAssured.baseURI=APIConstants.BASE_URI;
		
		RestAssured.given().auth().preemptive().
		basic(APIGlobalVariables.harvUsername, APIGlobalVariables.harvPassword).
		body(payload4)
		.contentType(ContentType.JSON).post().prettyPeek().then().
		assertThat().statusCode(200);
		
		//Scenario 4
		
		String payload5="{\r\n"
				+ "  \"customerId\": \"AI\",\r\n"
				+ "  \r\n"
				+ "  \"customerKey\": null,\r\n"
				+ "  \"quoteRequest\": {\r\n"
				+ "  \"productType\": \"DP3\",\r\n"
				+ "  \"producer\": \"AG6718A1\",\r\n"
				+ "  \"priorPolicy\": {\r\n"
				+ "    \"expirationDate\": \"2022-02-01\",\r\n"
				+ "    \"premium\": 1200,\r\n"
				+ "    \"carrier\": \"OTHER\",\r\n"
				+ "    \"originalEffectiveDate\": \"\",\r\n"
				+ "    \"priorPolicyNumber\": \"\"\r\n"
				+ "  },\r\n"
				+ "  \"entityType\": \"JOINT\",\r\n"
				+ "  \"insured\": {\r\n"
				+ "    \"name\": {\r\n"
				+ "      \"commercial\": \"Victor Hedman and Sanna Hedman\",\r\n"
				+ "      \"first\": \"Victor\",\r\n"
				+ "      \"middle\": \"\",\r\n"
				+ "      \"last\": \"Hedman\"\r\n"
				+ "    },\r\n"
				+ "    \"dateOfBirth\": \"1990-12-18\",\r\n"
				+ "    \"primaryPhone\": {\r\n"
				+ "      \"value\": \"(904)371-4627\",\r\n"
				+ "      \"name\": \"Victor Hedman\"\r\n"
				+ "    },\r\n"
				+ "    \"email\": \"\"\r\n"
				+ "  },\r\n"
				+ "  \"insuranceScore\": \"Better Than Average (750-849)\",\r\n"
				+ "  \"coInsured\": {\r\n"
				+ "    \"firstName\": \"Sanna\",\r\n"
				+ "    \"middleName\": \"\",\r\n"
				+ "    \"lastName\": \"Hedman\",\r\n"
				+ "    \"dateOfBirth\": \"1991-09-06\"\r\n"
				+ "  },\r\n"
				+ "  \"insuredProperty\": {\r\n"
				+ "    \"dwellingType\": \"SINGLE FAMILY\",\r\n"
				+ "      \"location\": {\r\n"
				+ "      \"address\": \"1710 E Kirby\",\r\n"
				+ "      \"city\": \"TAMPA\",\r\n"
				+ "      \"county\": \"Hillsborough\",\r\n"
				+ "      \"state\": \"FL\",\r\n"
				+ "      \"zipCode\": \"33604\"\r\n"
				+ "    },\r\n"
				+ "    \"bceg\": \"UNGRADED\",\r\n"
				+ "    \"constructionType\": \"FRAME\",\r\n"
				+ "    \"numberOfUnits\": 1,\r\n"
				+ "    \"occupancy\": \"OWNER\",\r\n"
				+ "    \"monthsOccupied\": 12,\r\n"
				+ "    \"numberOfStories\": 1,\r\n"
				+ "    \"storyUnitIsLocated\": 0,\r\n"
				+ "    \"distanceToCoast\": \"15 mi to less than 20 mi\"\r\n"
				+ "  },\r\n"
				+ "  \"dwelling\": {\r\n"
				+ "    \"distanceToHydrant\": \"LESS THAN OR EQUAL 1000 FEET\",\r\n"
				+ "    \"protectionClass\": 3,\r\n"
				+ "    \"squareFeet\": 1068,\r\n"
				+ "    \"yearOfConstruction\": 2018,\r\n"
				+ "    \"yearRoofMaterialUpdated\": 2018,\r\n"
				+ "    \"propertyManaged\": false,\r\n"
				+ "    \"shortTermRental\": false,\r\n"
				+ "    \"roofMaterial\": \"Concrete/Clay Tile\"\r\n"
				+ "  },\r\n"
				+ "  \"reservePackage\": \"INTEGRITYSELECT\",\r\n"
				+ "  \"deductibles\": {\r\n"
				+ "    \"aop\": 1000,\r\n"
				+ "    \"hurricane\": 10,\r\n"
				+ "    \"windHail\": 1000,\r\n"
				+ "    \"windHailExclusion\": false\r\n"
				+ "  },\r\n"
				+ "  \"coverages\": {\r\n"
				+ "    \"covA\": 450000,\r\n"
				+ "    \"covB\": 2,\r\n"
				+ "    \"covC\": 0,\r\n"
				+ "    \"covE\": 100000,\r\n"
				+ "    \"covF\": 5000,\r\n"
				+ "    \"covL\": 0,\r\n"
				+ "    \"covM\": 0,\r\n"
				+ "    \"homeComputer\": 2500,\r\n"
				+ "    \"homeSystemsProtection\": \"50000/10000\",\r\n"
				+ "    \"identityRecovery\": \"15000\",\r\n"
				+ "    \"lossAssessment\": 0,\r\n"
				+ "    \"fungiMoldEtc\": \"10000/10000\",\r\n"
				+ "    \"ordinanceOrLaw\": 0,\r\n"
				+ "    \"serviceLine\": \"None\",\r\n"
				+ "    \"waterBackupSumpOverflow\": \"\",\r\n"
				+ "    \"refrigeratedPersonalProperty\": false\r\n"
				+ "  },\r\n"
				+ "  \"optionalCoverages\": {\r\n"
				+ "    \"animalLiability\": true,\r\n"
				+ "    \"animalLiabilityAmount\": 0,\r\n"
				+ "    \"carportPoolCageScreen\": \"\",\r\n"
				+ "    \"increasedDwellingReplacementCost\": true,\r\n"
				+ "    \"limitedTheft\": false,\r\n"
				+ "    \"personalInjury\": false,\r\n"
				+ "    \"personalPropertyReplacementCost\": false,\r\n"
				+ "    \"sinkholeLoss\": \"10\",\r\n"
				+ "    \"waterDamageExclusion\": false,\r\n"
				+ "    \"waterDamageLimited\": false,\r\n"
				+ "    \"unitOwnersCovA\": false,\r\n"
				+ "    \"unitOwnersCovC\": false,\r\n"
				+ "    \"storageSlipRental\": false\r\n"
				+ "  },\r\n"
				+ "  \"discounts\": {\r\n"
				+ "    \"burglarAlarmCredit\": \"CENTRAL STATION\",\r\n"
				+ "    \"fireAlarmCredit\": \"CENTRAL STATION\",\r\n"
				+ "    \"proofOfUpdates\": \"ROOF ONLY\",\r\n"
				+ "    \"securedCommunityBldg\": \"\",\r\n"
				+ "    \"sprinklerSystem\": \"NONE\",\r\n"
				+ "    \"openFoundation\": false,\r\n"
				+ "    \"hardiplankSiding\": false,\r\n"
				+ "    \"military\": true\r\n"
				+ "  },\r\n"
				+ "  \"windMitigation\": {\r\n"
				+ "    \"openingProtection\": \"NONE\",\r\n"
				+ "    \"roofCover\": \"FBC EQUIVALENT\",\r\n"
				+ "    \"roofDeck\": \"\",\r\n"
				+ "    \"roofDeckAttachment\": \"\",\r\n"
				+ "    \"roofShape\": \"GABLE\",\r\n"
				+ "    \"roofToWallAttachment\": \"\",\r\n"
				+ "    \"secondaryWaterResistance\": false\r\n"
				+ "  },\r\n"
				+ "  \"effectiveDate\": \"2022-02-01\",\r\n"
				+ "   \"dataReports\": {\r\n"
				+ "  	\"runInsuranceScore\": false\r\n"
				+ "  }	\r\n"
				+ "} ,\r\n"
				+ "  \"requestId\": \"8720-88776\",\r\n"
				+ "  \"responseDetail\": true\r\n"
				+ "}";
		
		RestAssured.baseURI=APIConstants.BASE_URI;
		
		RestAssured.given().auth().preemptive().
		basic(APIGlobalVariables.harvUsername, APIGlobalVariables.harvPassword).
		body(payload5)
		.contentType(ContentType.JSON).post().prettyPeek().then().
		assertThat().statusCode(200);
		
		
		//Scenario5
		
		String payload6="{\r\n"
				+ "  \"customerId\": \"AI\",\r\n"
				+ "  \r\n"
				+ "  \"customerKey\": null,\r\n"
				+ "  \"quoteRequest\": {\r\n"
				+ "  \"productType\": \"DP3\",\r\n"
				+ "  \"producer\": \"AG6718A1\",\r\n"
				+ "  \"priorPolicy\": {\r\n"
				+ "    \"expirationDate\": \"2022-02-01\",\r\n"
				+ "    \"premium\": 1200,\r\n"
				+ "    \"carrier\": \"OTHER\",\r\n"
				+ "    \"originalEffectiveDate\": \"\",\r\n"
				+ "    \"priorPolicyNumber\": \"\"\r\n"
				+ "  },\r\n"
				+ "  \"entityType\": \"JOINT\",\r\n"
				+ "  \"insured\": {\r\n"
				+ "    \"name\": {\r\n"
				+ "      \"commercial\": \"Victor Hedman and Sanna Hedman\",\r\n"
				+ "      \"first\": \"Victor\",\r\n"
				+ "      \"middle\": \"\",\r\n"
				+ "      \"last\": \"Hedman\"\r\n"
				+ "    },\r\n"
				+ "    \"dateOfBirth\": \"1990-12-18\",\r\n"
				+ "    \"primaryPhone\": {\r\n"
				+ "      \"value\": \"(904)371-4627\",\r\n"
				+ "      \"name\": \"Victor Hedman\"\r\n"
				+ "    },\r\n"
				+ "    \"email\": \"\"\r\n"
				+ "  },\r\n"
				+ "  \"insuranceScore\": \"Better Than Average (750-849)\",\r\n"
				+ "  \"coInsured\": {\r\n"
				+ "    \"firstName\": \"Sanna\",\r\n"
				+ "    \"middleName\": \"\",\r\n"
				+ "    \"lastName\": \"Hedman\",\r\n"
				+ "    \"dateOfBirth\": \"1991-09-06\"\r\n"
				+ "  },\r\n"
				+ "  \"insuredProperty\": {\r\n"
				+ "    \"dwellingType\": \"SINGLE FAMILY\",\r\n"
				+ "      \"location\": {\r\n"
				+ "      \"address\": \"1710 E Kirby\",\r\n"
				+ "      \"city\": \"TAMPA\",\r\n"
				+ "      \"county\": \"Hillsborough\",\r\n"
				+ "      \"state\": \"FL\",\r\n"
				+ "      \"zipCode\": \"33604\"\r\n"
				+ "    },\r\n"
				+ "    \"bceg\": \"UNGRADED\",\r\n"
				+ "    \"constructionType\": \"FRAME\",\r\n"
				+ "    \"numberOfUnits\": 1,\r\n"
				+ "    \"occupancy\": \"OWNER\",\r\n"
				+ "    \"monthsOccupied\": 12,\r\n"
				+ "    \"numberOfStories\": 1,\r\n"
				+ "    \"storyUnitIsLocated\": 0,\r\n"
				+ "    \"distanceToCoast\": \"15 mi to less than 20 mi\"\r\n"
				+ "  },\r\n"
				+ "  \"dwelling\": {\r\n"
				+ "    \"distanceToHydrant\": \"LESS THAN OR EQUAL 1000 FEET\",\r\n"
				+ "    \"protectionClass\": 3,\r\n"
				+ "    \"squareFeet\": 1068,\r\n"
				+ "    \"yearOfConstruction\": 2018,\r\n"
				+ "    \"yearRoofMaterialUpdated\": 2018,\r\n"
				+ "    \"propertyManaged\": false,\r\n"
				+ "    \"shortTermRental\": false,\r\n"
				+ "    \"roofMaterial\": \"Concrete/Clay Tile\"\r\n"
				+ "  },\r\n"
				+ "  \"reservePackage\": \"INTEGRITYSELECT\",\r\n"
				+ "  \"deductibles\": {\r\n"
				+ "    \"aop\": 1000,\r\n"
				+ "    \"hurricane\": 10,\r\n"
				+ "    \"windHail\": 1000,\r\n"
				+ "    \"windHailExclusion\": false\r\n"
				+ "  },\r\n"
				+ "  \"coverages\": {\r\n"
				+ "    \"covA\": 500000,\r\n"
				+ "    \"covB\": 2,\r\n"
				+ "    \"covC\": 120000,\r\n"
				+ "    \"covE\": 100000,\r\n"
				+ "    \"covF\": 5000,\r\n"
				+ "    \"covL\": 0,\r\n"
				+ "    \"covM\": 0,\r\n"
				+ "    \"homeComputer\": 2500,\r\n"
				+ "    \"homeSystemsProtection\": \"50000/10000\",\r\n"
				+ "    \"identityRecovery\": \"15000\",\r\n"
				+ "    \"lossAssessment\": 0,\r\n"
				+ "    \"fungiMoldEtc\": \"10000/10000\",\r\n"
				+ "    \"ordinanceOrLaw\": 0,\r\n"
				+ "    \"serviceLine\": \"None\",\r\n"
				+ "    \"waterBackupSumpOverflow\": \"\",\r\n"
				+ "    \"refrigeratedPersonalProperty\": false\r\n"
				+ "  },\r\n"
				+ "  \"optionalCoverages\": {\r\n"
				+ "    \"animalLiability\": true,\r\n"
				+ "    \"animalLiabilityAmount\": 0,\r\n"
				+ "    \"carportPoolCageScreen\": \"\",\r\n"
				+ "    \"increasedDwellingReplacementCost\": true,\r\n"
				+ "    \"limitedTheft\": false,\r\n"
				+ "    \"personalInjury\": false,\r\n"
				+ "    \"personalPropertyReplacementCost\": false,\r\n"
				+ "    \"sinkholeLoss\": \"10\",\r\n"
				+ "    \"waterDamageExclusion\": false,\r\n"
				+ "    \"waterDamageLimited\": false,\r\n"
				+ "    \"unitOwnersCovA\": false,\r\n"
				+ "    \"unitOwnersCovC\": false,\r\n"
				+ "    \"storageSlipRental\": false\r\n"
				+ "  },\r\n"
				+ "  \"discounts\": {\r\n"
				+ "    \"burglarAlarmCredit\": \"CENTRAL STATION\",\r\n"
				+ "    \"fireAlarmCredit\": \"CENTRAL STATION\",\r\n"
				+ "    \"proofOfUpdates\": \"ROOF ONLY\",\r\n"
				+ "    \"securedCommunityBldg\": \"\",\r\n"
				+ "    \"sprinklerSystem\": \"NONE\",\r\n"
				+ "    \"openFoundation\": false,\r\n"
				+ "    \"hardiplankSiding\": false,\r\n"
				+ "    \"military\": true\r\n"
				+ "  },\r\n"
				+ "  \"windMitigation\": {\r\n"
				+ "    \"openingProtection\": \"NONE\",\r\n"
				+ "    \"roofCover\": \"FBC EQUIVALENT\",\r\n"
				+ "    \"roofDeck\": \"\",\r\n"
				+ "    \"roofDeckAttachment\": \"\",\r\n"
				+ "    \"roofShape\": \"GABLE\",\r\n"
				+ "    \"roofToWallAttachment\": \"\",\r\n"
				+ "    \"secondaryWaterResistance\": false\r\n"
				+ "  },\r\n"
				+ "  \"effectiveDate\": \"2022-02-01\",\r\n"
				+ "   \"dataReports\": {\r\n"
				+ "  	\"runInsuranceScore\": false\r\n"
				+ "  }	\r\n"
				+ "} ,\r\n"
				+ "  \"requestId\": \"8720-88776\",\r\n"
				+ "  \"responseDetail\": true\r\n"
				+ "}";
		
		RestAssured.baseURI=APIConstants.BASE_URI;
		
		RestAssured.given().auth().preemptive().
		basic(APIGlobalVariables.harvUsername, APIGlobalVariables.harvPassword).
		body(payload6)
		.contentType(ContentType.JSON).post().prettyPeek().then().
		assertThat().statusCode(200);
			
		System.out.println("All scenarios have passed for US-5965");
}

//Validation of US-6287 Rules Coverage A Minimum Limit Change
@Test
@When("I enter required body information for required scenarios <US6287> and I validate response body status code is ok")
public void i_enter_required_body_information_for_required_scenarios_us6287_and_i_validate_response_body_status_code_is_ok() {
    
	//Scenario 1
	
	String payload1="{\r\n"
			+ "  \"customerId\": \"AI\",\r\n"
			+ "  \r\n"
			+ "  \"customerKey\": null,\r\n"
			+ "  \"quoteRequest\": {\r\n"
			+ "  \"productType\": \"DP3\",\r\n"
			+ "  \"producer\": \"AG6718A1\",\r\n"
			+ "  \"priorPolicy\": {\r\n"
			+ "    \"expirationDate\": \"2022-02-01\",\r\n"
			+ "    \"premium\": 1200,\r\n"
			+ "    \"carrier\": \"OTHER\",\r\n"
			+ "    \"originalEffectiveDate\": \"\",\r\n"
			+ "    \"priorPolicyNumber\": \"\"\r\n"
			+ "  },\r\n"
			+ "  \"entityType\": \"JOINT\",\r\n"
			+ "  \"insured\": {\r\n"
			+ "    \"name\": {\r\n"
			+ "      \"commercial\": \"Victor Hedman and Sanna Hedman\",\r\n"
			+ "      \"first\": \"Victor\",\r\n"
			+ "      \"middle\": \"\",\r\n"
			+ "      \"last\": \"Hedman\"\r\n"
			+ "    },\r\n"
			+ "    \"dateOfBirth\": \"1990-12-18\",\r\n"
			+ "    \"primaryPhone\": {\r\n"
			+ "      \"value\": \"(904)371-4627\",\r\n"
			+ "      \"name\": \"Victor Hedman\"\r\n"
			+ "    },\r\n"
			+ "    \"email\": \"\"\r\n"
			+ "  },\r\n"
			+ "  \"insuranceScore\": \"\",\r\n"
			+ "  \"coInsured\": {\r\n"
			+ "    \"firstName\": \"Sanna\",\r\n"
			+ "    \"middleName\": \"\",\r\n"
			+ "    \"lastName\": \"Hedman\",\r\n"
			+ "    \"dateOfBirth\": \"1991-09-06\"\r\n"
			+ "  },\r\n"
			+ "  \"insuredProperty\": {\r\n"
			+ "    \"dwellingType\": \"SINGLE FAMILY\",\r\n"
			+ "      \"location\": {\r\n"
			+ "      \"address\": \"1710 E Kirby\",\r\n"
			+ "      \"city\": \"TAMPA\",\r\n"
			+ "      \"county\": \"Hillsborough\",\r\n"
			+ "      \"state\": \"FL\",\r\n"
			+ "      \"zipCode\": \"33604\"\r\n"
			+ "    },\r\n"
			+ "    \"bceg\": \"UNGRADED\",\r\n"
			+ "    \"constructionType\": \"FRAME\",\r\n"
			+ "    \"numberOfUnits\": 1,\r\n"
			+ "    \"occupancy\": \"OWNER\",\r\n"
			+ "    \"monthsOccupied\": 12,\r\n"
			+ "    \"numberOfStories\": 1,\r\n"
			+ "    \"storyUnitIsLocated\": 0,\r\n"
			+ "    \"distanceToCoast\": \"15 mi to less than 20 mi\"\r\n"
			+ "  },\r\n"
			+ "  \"dwelling\": {\r\n"
			+ "    \"distanceToHydrant\": \"LESS THAN OR EQUAL 1000 FEET\",\r\n"
			+ "    \"protectionClass\": 3,\r\n"
			+ "    \"squareFeet\": 1068,\r\n"
			+ "    \"yearOfConstruction\": 2018,\r\n"
			+ "    \"yearRoofMaterialUpdated\": 2018,\r\n"
			+ "    \"propertyManaged\": false,\r\n"
			+ "    \"shortTermRental\": false,\r\n"
			+ "    \"roofMaterial\": \"Concrete/Clay Tile\"\r\n"
			+ "  },\r\n"
			+ "  \"reservePackage\": \"INTEGRITYSELECT\",\r\n"
			+ "  \"deductibles\": {\r\n"
			+ "    \"aop\": 1000,\r\n"
			+ "    \"hurricane\": 10,\r\n"
			+ "    \"windHail\": 1000,\r\n"
			+ "    \"windHailExclusion\": false\r\n"
			+ "  },\r\n"
			+ "  \"coverages\": {\r\n"
			+ "    \"covA\": 120000,\r\n"
			+ "    \"covB\": 2,\r\n"
			+ "    \"covC\": 70000,\r\n"
			+ "    \"covE\": 70000,\r\n"
			+ "    \"covF\": 5000,\r\n"
			+ "    \"covL\": 100000,\r\n"
			+ "    \"covM\": 0,\r\n"
			+ "    \"homeComputer\": 2500,\r\n"
			+ "    \"homeSystemsProtection\": \"50000/10000\",\r\n"
			+ "    \"identityRecovery\": \"15000\",\r\n"
			+ "    \"fungiMoldEtc\": \"10000/10000\",\r\n"
			+ "    \"ordinanceOrLaw\": 0,\r\n"
			+ "    \"serviceLine\": \"None\",\r\n"
			+ "    \"waterBackupSumpOverflow\": \"\",\r\n"
			+ "    \"refrigeratedPersonalProperty\": true\r\n"
			+ "  },\r\n"
			+ "  \"optionalCoverages\": {\r\n"
			+ "    \"animalLiability\": true,\r\n"
			+ "    \"animalLiabilityAmount\": 50000,\r\n"
			+ "    \"carportPoolCageScreen\": \"\",\r\n"
			+ "    \"increasedDwellingReplacementCost\": true,\r\n"
			+ "    \"limitedTheft\": false,\r\n"
			+ "    \"personalInjury\": true,\r\n"
			+ "    \"personalPropertyReplacementCost\": false,\r\n"
			+ "    \"sinkholeLoss\": \"10\",\r\n"
			+ "    \"waterDamageExclusion\": false,\r\n"
			+ "    \"waterDamageLimited\": false,\r\n"
			+ "    \"unitOwnersCovA\": false,\r\n"
			+ "    \"unitOwnersCovC\": false,\r\n"
			+ "    \"storageSlipRental\": false\r\n"
			+ "  },\r\n"
			+ "  \"discounts\": {\r\n"
			+ "    \"burglarAlarmCredit\": \"CENTRAL STATION\",\r\n"
			+ "    \"fireAlarmCredit\": \"CENTRAL STATION\",\r\n"
			+ "    \"proofOfUpdates\": \"ROOF ONLY\",\r\n"
			+ "    \"securedCommunityBldg\": \"\",\r\n"
			+ "    \"sprinklerSystem\": \"NONE\",\r\n"
			+ "    \"openFoundation\": false,\r\n"
			+ "    \"hardiplankSiding\": false,\r\n"
			+ "    \"military\": true\r\n"
			+ "  },\r\n"
			+ "  \"windMitigation\": {\r\n"
			+ "    \"openingProtection\": \"NONE\",\r\n"
			+ "    \"roofCover\": \"FBC EQUIVALENT\",\r\n"
			+ "    \"roofDeck\": \"\",\r\n"
			+ "    \"roofDeckAttachment\": \"\",\r\n"
			+ "    \"roofShape\": \"GABLE\",\r\n"
			+ "    \"roofToWallAttachment\": \"\",\r\n"
			+ "    \"secondaryWaterResistance\": false\r\n"
			+ "  },\r\n"
			+ "  \"effectiveDate\": \"2022-02-01\",\r\n"
			+ "   \"dataReports\": {\r\n"
			+ "  	\"runInsuranceScore\": false\r\n"
			+ "  }	\r\n"
			+ "} ,\r\n"
			+ "  \"requestId\": \"8720-88776\",\r\n"
			+ "  \"responseDetail\": true\r\n"
			+ "}";
	
	RestAssured.baseURI=APIConstants.BASE_URI;
	
	RestAssured.given().auth().preemptive().
	basic(APIGlobalVariables.harvUsername, APIGlobalVariables.harvPassword).
	body(payload1)
	.contentType(ContentType.JSON).post().prettyPeek().then().
	assertThat().statusCode(200);
	
	//Scenario2
	String payload2="{\r\n"
			+ "  \"customerId\": \"AI\",\r\n"
			+ "  \r\n"
			+ "  \"customerKey\": null,\r\n"
			+ "  \"quoteRequest\": {\r\n"
			+ "  \"productType\": \"DP3\",\r\n"
			+ "  \"producer\": \"AG6718A1\",\r\n"
			+ "  \"priorPolicy\": {\r\n"
			+ "    \"expirationDate\": \"2022-02-01\",\r\n"
			+ "    \"premium\": 1200,\r\n"
			+ "    \"carrier\": \"OTHER\",\r\n"
			+ "    \"originalEffectiveDate\": \"\",\r\n"
			+ "    \"priorPolicyNumber\": \"\"\r\n"
			+ "  },\r\n"
			+ "  \"entityType\": \"JOINT\",\r\n"
			+ "  \"insured\": {\r\n"
			+ "    \"name\": {\r\n"
			+ "      \"commercial\": \"Victor Hedman and Sanna Hedman\",\r\n"
			+ "      \"first\": \"Victor\",\r\n"
			+ "      \"middle\": \"\",\r\n"
			+ "      \"last\": \"Hedman\"\r\n"
			+ "    },\r\n"
			+ "    \"dateOfBirth\": \"1990-12-18\",\r\n"
			+ "    \"primaryPhone\": {\r\n"
			+ "      \"value\": \"(904)371-4627\",\r\n"
			+ "      \"name\": \"Victor Hedman\"\r\n"
			+ "    },\r\n"
			+ "    \"email\": \"\"\r\n"
			+ "  },\r\n"
			+ "  \"insuranceScore\": \"\",\r\n"
			+ "  \"coInsured\": {\r\n"
			+ "    \"firstName\": \"Sanna\",\r\n"
			+ "    \"middleName\": \"\",\r\n"
			+ "    \"lastName\": \"Hedman\",\r\n"
			+ "    \"dateOfBirth\": \"1991-09-06\"\r\n"
			+ "  },\r\n"
			+ "  \"insuredProperty\": {\r\n"
			+ "    \"dwellingType\": \"SINGLE FAMILY\",\r\n"
			+ "      \"location\": {\r\n"
			+ "      \"address\": \"1710 E Kirby\",\r\n"
			+ "      \"city\": \"TAMPA\",\r\n"
			+ "      \"county\": \"Hillsborough\",\r\n"
			+ "      \"state\": \"FL\",\r\n"
			+ "      \"zipCode\": \"33604\"\r\n"
			+ "    },\r\n"
			+ "    \"bceg\": \"UNGRADED\",\r\n"
			+ "    \"constructionType\": \"FRAME\",\r\n"
			+ "    \"numberOfUnits\": 1,\r\n"
			+ "    \"occupancy\": \"OWNER\",\r\n"
			+ "    \"monthsOccupied\": 12,\r\n"
			+ "    \"numberOfStories\": 1,\r\n"
			+ "    \"storyUnitIsLocated\": 0,\r\n"
			+ "    \"distanceToCoast\": \"15 mi to less than 20 mi\"\r\n"
			+ "  },\r\n"
			+ "  \"dwelling\": {\r\n"
			+ "    \"distanceToHydrant\": \"LESS THAN OR EQUAL 1000 FEET\",\r\n"
			+ "    \"protectionClass\": 3,\r\n"
			+ "    \"squareFeet\": 1068,\r\n"
			+ "    \"yearOfConstruction\": 2018,\r\n"
			+ "    \"yearRoofMaterialUpdated\": 2018,\r\n"
			+ "    \"propertyManaged\": false,\r\n"
			+ "    \"shortTermRental\": false,\r\n"
			+ "    \"roofMaterial\": \"Concrete/Clay Tile\"\r\n"
			+ "  },\r\n"
			+ "  \"reservePackage\": \"INTEGRITYSELECT\",\r\n"
			+ "  \"deductibles\": {\r\n"
			+ "    \"aop\": 1000,\r\n"
			+ "    \"hurricane\": 10,\r\n"
			+ "    \"windHail\": 1000,\r\n"
			+ "    \"windHailExclusion\": false\r\n"
			+ "  },\r\n"
			+ "  \"coverages\": {\r\n"
			+ "    \"covA\": 350000,\r\n"
			+ "    \"covB\": 2,\r\n"
			+ "    \"covC\": 100000,\r\n"
			+ "    \"covE\": 100000,\r\n"
			+ "    \"covF\": 5000,\r\n"
			+ "    \"covL\": 100000,\r\n"
			+ "    \"covM\": 0,\r\n"
			+ "    \"homeComputer\": 2500,\r\n"
			+ "    \"homeSystemsProtection\": \"50000/10000\",\r\n"
			+ "    \"identityRecovery\": \"15000\",\r\n"
			+ "    \"fungiMoldEtc\": \"10000/10000\",\r\n"
			+ "    \"ordinanceOrLaw\": 0,\r\n"
			+ "    \"serviceLine\": \"None\",\r\n"
			+ "    \"waterBackupSumpOverflow\": \"\",\r\n"
			+ "    \"refrigeratedPersonalProperty\": true\r\n"
			+ "  },\r\n"
			+ "  \"optionalCoverages\": {\r\n"
			+ "    \"animalLiability\": true,\r\n"
			+ "    \"animalLiabilityAmount\": 50000,\r\n"
			+ "    \"carportPoolCageScreen\": \"\",\r\n"
			+ "    \"increasedDwellingReplacementCost\": true,\r\n"
			+ "    \"limitedTheft\": false,\r\n"
			+ "    \"personalInjury\": true,\r\n"
			+ "    \"personalPropertyReplacementCost\": false,\r\n"
			+ "    \"sinkholeLoss\": \"10\",\r\n"
			+ "    \"waterDamageExclusion\": false,\r\n"
			+ "    \"waterDamageLimited\": false,\r\n"
			+ "    \"unitOwnersCovA\": false,\r\n"
			+ "    \"unitOwnersCovC\": false,\r\n"
			+ "    \"storageSlipRental\": false\r\n"
			+ "  },\r\n"
			+ "  \"discounts\": {\r\n"
			+ "    \"burglarAlarmCredit\": \"CENTRAL STATION\",\r\n"
			+ "    \"fireAlarmCredit\": \"CENTRAL STATION\",\r\n"
			+ "    \"proofOfUpdates\": \"ROOF ONLY\",\r\n"
			+ "    \"securedCommunityBldg\": \"\",\r\n"
			+ "    \"sprinklerSystem\": \"NONE\",\r\n"
			+ "    \"openFoundation\": false,\r\n"
			+ "    \"hardiplankSiding\": false,\r\n"
			+ "    \"military\": true\r\n"
			+ "  },\r\n"
			+ "  \"windMitigation\": {\r\n"
			+ "    \"openingProtection\": \"NONE\",\r\n"
			+ "    \"roofCover\": \"FBC EQUIVALENT\",\r\n"
			+ "    \"roofDeck\": \"\",\r\n"
			+ "    \"roofDeckAttachment\": \"\",\r\n"
			+ "    \"roofShape\": \"GABLE\",\r\n"
			+ "    \"roofToWallAttachment\": \"\",\r\n"
			+ "    \"secondaryWaterResistance\": false\r\n"
			+ "  },\r\n"
			+ "  \"effectiveDate\": \"2022-02-01\",\r\n"
			+ "   \"dataReports\": {\r\n"
			+ "  	\"runInsuranceScore\": false\r\n"
			+ "  }	\r\n"
			+ "} ,\r\n"
			+ "  \"requestId\": \"8720-88776\",\r\n"
			+ "  \"responseDetail\": true\r\n"
			+ "}";
	
	
	RestAssured.baseURI=APIConstants.BASE_URI;
	
	RestAssured.given().auth().preemptive().
	basic(APIGlobalVariables.harvUsername, APIGlobalVariables.harvPassword).
	body(payload2)
	.contentType(ContentType.JSON).post().prettyPeek().then().
	assertThat().statusCode(200);
	
	
	//Scenario3
	
	String payload3="{\r\n"
			+ "  \"customerId\": \"AI\",\r\n"
			+ "  \r\n"
			+ "  \"customerKey\": null,\r\n"
			+ "  \"quoteRequest\": {\r\n"
			+ "  \"productType\": \"DP3\",\r\n"
			+ "  \"producer\": \"AG6718A1\",\r\n"
			+ "  \"priorPolicy\": {\r\n"
			+ "    \"expirationDate\": \"2022-02-01\",\r\n"
			+ "    \"premium\": 1200,\r\n"
			+ "    \"carrier\": \"OTHER\",\r\n"
			+ "    \"originalEffectiveDate\": \"\",\r\n"
			+ "    \"priorPolicyNumber\": \"\"\r\n"
			+ "  },\r\n"
			+ "  \"entityType\": \"JOINT\",\r\n"
			+ "  \"insured\": {\r\n"
			+ "    \"name\": {\r\n"
			+ "      \"commercial\": \"Victor Hedman and Sanna Hedman\",\r\n"
			+ "      \"first\": \"Victor\",\r\n"
			+ "      \"middle\": \"\",\r\n"
			+ "      \"last\": \"Hedman\"\r\n"
			+ "    },\r\n"
			+ "    \"dateOfBirth\": \"1990-12-18\",\r\n"
			+ "    \"primaryPhone\": {\r\n"
			+ "      \"value\": \"(904)371-4627\",\r\n"
			+ "      \"name\": \"Victor Hedman\"\r\n"
			+ "    },\r\n"
			+ "    \"email\": \"\"\r\n"
			+ "  },\r\n"
			+ "  \"insuranceScore\": \"\",\r\n"
			+ "  \"coInsured\": {\r\n"
			+ "    \"firstName\": \"Sanna\",\r\n"
			+ "    \"middleName\": \"\",\r\n"
			+ "    \"lastName\": \"Hedman\",\r\n"
			+ "    \"dateOfBirth\": \"1991-09-06\"\r\n"
			+ "  },\r\n"
			+ "  \"insuredProperty\": {\r\n"
			+ "    \"dwellingType\": \"SINGLE FAMILY\",\r\n"
			+ "      \"location\": {\r\n"
			+ "      \"address\": \"1710 E Kirby\",\r\n"
			+ "      \"city\": \"TAMPA\",\r\n"
			+ "      \"county\": \"Hillsborough\",\r\n"
			+ "      \"state\": \"FL\",\r\n"
			+ "      \"zipCode\": \"33604\"\r\n"
			+ "    },\r\n"
			+ "    \"bceg\": \"UNGRADED\",\r\n"
			+ "    \"constructionType\": \"FRAME\",\r\n"
			+ "    \"numberOfUnits\": 1,\r\n"
			+ "    \"occupancy\": \"ONWER\",\r\n"
			+ "    \"monthsOccupied\": 12,\r\n"
			+ "    \"numberOfStories\": 1,\r\n"
			+ "    \"storyUnitIsLocated\": 0,\r\n"
			+ "    \"distanceToCoast\": \"15 mi to less than 20 mi\"\r\n"
			+ "  },\r\n"
			+ "  \"dwelling\": {\r\n"
			+ "    \"distanceToHydrant\": \"LESS THAN OR EQUAL 1000 FEET\",\r\n"
			+ "    \"protectionClass\": 3,\r\n"
			+ "    \"squareFeet\": 1068,\r\n"
			+ "    \"yearOfConstruction\": 2018,\r\n"
			+ "    \"yearRoofMaterialUpdated\": 2018,\r\n"
			+ "    \"propertyManaged\": false,\r\n"
			+ "    \"shortTermRental\": false,\r\n"
			+ "    \"roofMaterial\": \"Concrete/Clay Tile\"\r\n"
			+ "  },\r\n"
			+ "  \"reservePackage\": \"INTEGRITYSELECT\",\r\n"
			+ "  \"deductibles\": {\r\n"
			+ "    \"aop\": 1000,\r\n"
			+ "    \"hurricane\": 10,\r\n"
			+ "    \"windHail\": 1000,\r\n"
			+ "    \"windHailExclusion\": false\r\n"
			+ "  },\r\n"
			+ "  \"coverages\": {\r\n"
			+ "    \"covA\": 350000,\r\n"
			+ "    \"covB\": 2,\r\n"
			+ "    \"covC\": 100000,\r\n"
			+ "    \"covE\": 100000,\r\n"
			+ "    \"covF\": 5000,\r\n"
			+ "    \"covL\": 100000,\r\n"
			+ "    \"covM\": 0,\r\n"
			+ "    \"homeComputer\": 2500,\r\n"
			+ "    \"homeSystemsProtection\": \"50000/10000\",\r\n"
			+ "    \"identityRecovery\": \"15000\",\r\n"
			+ "    \"fungiMoldEtc\": \"10000/10000\",\r\n"
			+ "    \"ordinanceOrLaw\": 0,\r\n"
			+ "    \"serviceLine\": \"None\",\r\n"
			+ "    \"waterBackupSumpOverflow\": \"\",\r\n"
			+ "    \"refrigeratedPersonalProperty\": true\r\n"
			+ "  },\r\n"
			+ "  \"optionalCoverages\": {\r\n"
			+ "    \"animalLiability\": true,\r\n"
			+ "    \"animalLiabilityAmount\": 50000,\r\n"
			+ "    \"carportPoolCageScreen\": \"\",\r\n"
			+ "    \"increasedDwellingReplacementCost\": true,\r\n"
			+ "    \"limitedTheft\": false,\r\n"
			+ "    \"personalInjury\": true,\r\n"
			+ "    \"personalPropertyReplacementCost\": false,\r\n"
			+ "    \"sinkholeLoss\": \"10\",\r\n"
			+ "    \"waterDamageExclusion\": false,\r\n"
			+ "    \"waterDamageLimited\": false,\r\n"
			+ "    \"unitOwnersCovA\": false,\r\n"
			+ "    \"unitOwnersCovC\": false,\r\n"
			+ "    \"storageSlipRental\": false\r\n"
			+ "  },\r\n"
			+ "  \"discounts\": {\r\n"
			+ "    \"burglarAlarmCredit\": \"CENTRAL STATION\",\r\n"
			+ "    \"fireAlarmCredit\": \"CENTRAL STATION\",\r\n"
			+ "    \"proofOfUpdates\": \"ROOF ONLY\",\r\n"
			+ "    \"securedCommunityBldg\": \"\",\r\n"
			+ "    \"sprinklerSystem\": \"NONE\",\r\n"
			+ "    \"openFoundation\": false,\r\n"
			+ "    \"hardiplankSiding\": false,\r\n"
			+ "    \"military\": true\r\n"
			+ "  },\r\n"
			+ "  \"windMitigation\": {\r\n"
			+ "    \"openingProtection\": \"NONE\",\r\n"
			+ "    \"roofCover\": \"FBC EQUIVALENT\",\r\n"
			+ "    \"roofDeck\": \"\",\r\n"
			+ "    \"roofDeckAttachment\": \"\",\r\n"
			+ "    \"roofShape\": \"GABLE\",\r\n"
			+ "    \"roofToWallAttachment\": \"\",\r\n"
			+ "    \"secondaryWaterResistance\": false\r\n"
			+ "  },\r\n"
			+ "  \"effectiveDate\": \"2022-02-01\",\r\n"
			+ "   \"dataReports\": {\r\n"
			+ "  	\"runInsuranceScore\": false\r\n"
			+ "  }	\r\n"
			+ "} ,\r\n"
			+ "  \"requestId\": \"8720-88776\",\r\n"
			+ "  \"responseDetail\": true\r\n"
			+ "}";
	
	RestAssured.baseURI=APIConstants.BASE_URI;
	
	RestAssured.given().auth().preemptive().
	basic(APIGlobalVariables.harvUsername, APIGlobalVariables.harvPassword).
	body(payload3)
	.contentType(ContentType.JSON).post().prettyPeek().then().
	assertThat().statusCode(200);
	
	//Scenario 4
	
	String payload4="{\r\n"
			+ "  \"customerId\": \"AI\",\r\n"
			+ "  \r\n"
			+ "  \"customerKey\": null,\r\n"
			+ "  \"quoteRequest\": {\r\n"
			+ "  \"productType\": \"DP3\",\r\n"
			+ "  \"producer\": \"AG6718A1\",\r\n"
			+ "  \"priorPolicy\": {\r\n"
			+ "    \"expirationDate\": \"2022-02-01\",\r\n"
			+ "    \"premium\": 1200,\r\n"
			+ "    \"carrier\": \"OTHER\",\r\n"
			+ "    \"originalEffectiveDate\": \"\",\r\n"
			+ "    \"priorPolicyNumber\": \"\"\r\n"
			+ "  },\r\n"
			+ "  \"entityType\": \"JOINT\",\r\n"
			+ "  \"insured\": {\r\n"
			+ "    \"name\": {\r\n"
			+ "      \"commercial\": \"Victor Hedman and Sanna Hedman\",\r\n"
			+ "      \"first\": \"Victor\",\r\n"
			+ "      \"middle\": \"\",\r\n"
			+ "      \"last\": \"Hedman\"\r\n"
			+ "    },\r\n"
			+ "    \"dateOfBirth\": \"1990-12-18\",\r\n"
			+ "    \"primaryPhone\": {\r\n"
			+ "      \"value\": \"(904)371-4627\",\r\n"
			+ "      \"name\": \"Victor Hedman\"\r\n"
			+ "    },\r\n"
			+ "    \"email\": \"\"\r\n"
			+ "  },\r\n"
			+ "  \"insuranceScore\": \"\",\r\n"
			+ "  \"coInsured\": {\r\n"
			+ "    \"firstName\": \"Sanna\",\r\n"
			+ "    \"middleName\": \"\",\r\n"
			+ "    \"lastName\": \"Hedman\",\r\n"
			+ "    \"dateOfBirth\": \"1991-09-06\"\r\n"
			+ "  },\r\n"
			+ "  \"insuredProperty\": {\r\n"
			+ "    \"dwellingType\": \"SINGLE FAMILY\",\r\n"
			+ "      \"location\": {\r\n"
			+ "      \"address\": \"1710 E Kirby\",\r\n"
			+ "      \"city\": \"TAMPA\",\r\n"
			+ "      \"county\": \"Hillsborough\",\r\n"
			+ "      \"state\": \"FL\",\r\n"
			+ "      \"zipCode\": \"33604\"\r\n"
			+ "    },\r\n"
			+ "    \"bceg\": \"UNGRADED\",\r\n"
			+ "    \"constructionType\": \"FRAME\",\r\n"
			+ "    \"numberOfUnits\": 1,\r\n"
			+ "    \"occupancy\": \"OWNER\",\r\n"
			+ "    \"monthsOccupied\": 12,\r\n"
			+ "    \"numberOfStories\": 1,\r\n"
			+ "    \"storyUnitIsLocated\": 0,\r\n"
			+ "    \"distanceToCoast\": \"15 mi to less than 20 mi\"\r\n"
			+ "  },\r\n"
			+ "  \"dwelling\": {\r\n"
			+ "    \"distanceToHydrant\": \"LESS THAN OR EQUAL 1000 FEET\",\r\n"
			+ "    \"protectionClass\": 3,\r\n"
			+ "    \"squareFeet\": 1068,\r\n"
			+ "    \"yearOfConstruction\": 2018,\r\n"
			+ "    \"yearRoofMaterialUpdated\": 2018,\r\n"
			+ "    \"propertyManaged\": false,\r\n"
			+ "    \"shortTermRental\": false,\r\n"
			+ "    \"roofMaterial\": \"Concrete/Clay Tile\"\r\n"
			+ "  },\r\n"
			+ "  \"reservePackage\": \"INTEGRITYSELECT\",\r\n"
			+ "  \"deductibles\": {\r\n"
			+ "    \"aop\": 1000,\r\n"
			+ "    \"hurricane\": 10,\r\n"
			+ "    \"windHail\": 1000,\r\n"
			+ "    \"windHailExclusion\": false\r\n"
			+ "  },\r\n"
			+ "  \"coverages\": {\r\n"
			+ "    \"covA\": 350000,\r\n"
			+ "    \"covB\": 2,\r\n"
			+ "    \"covC\": 100000,\r\n"
			+ "    \"covE\": 100000,\r\n"
			+ "    \"covF\": 5000,\r\n"
			+ "    \"covL\": 100000,\r\n"
			+ "    \"covM\": 0,\r\n"
			+ "    \"homeComputer\": 2500,\r\n"
			+ "    \"homeSystemsProtection\": \"50000/10000\",\r\n"
			+ "    \"identityRecovery\": \"15000\",\r\n"
			+ "    \"fungiMoldEtc\": \"10000/10000\",\r\n"
			+ "    \"ordinanceOrLaw\": 0,\r\n"
			+ "    \"serviceLine\": \"None\",\r\n"
			+ "    \"waterBackupSumpOverflow\": \"\",\r\n"
			+ "    \"refrigeratedPersonalProperty\": true\r\n"
			+ "  },\r\n"
			+ "  \"optionalCoverages\": {\r\n"
			+ "    \"animalLiability\": true,\r\n"
			+ "    \"animalLiabilityAmount\": 50000,\r\n"
			+ "    \"carportPoolCageScreen\": \"\",\r\n"
			+ "    \"increasedDwellingReplacementCost\": true,\r\n"
			+ "    \"limitedTheft\": false,\r\n"
			+ "    \"personalInjury\": true,\r\n"
			+ "    \"personalPropertyReplacementCost\": false,\r\n"
			+ "    \"sinkholeLoss\": \"10\",\r\n"
			+ "    \"waterDamageExclusion\": false,\r\n"
			+ "    \"waterDamageLimited\": false,\r\n"
			+ "    \"unitOwnersCovA\": false,\r\n"
			+ "    \"unitOwnersCovC\": false,\r\n"
			+ "    \"storageSlipRental\": false\r\n"
			+ "  },\r\n"
			+ "  \"discounts\": {\r\n"
			+ "    \"burglarAlarmCredit\": \"CENTRAL STATION\",\r\n"
			+ "    \"fireAlarmCredit\": \"CENTRAL STATION\",\r\n"
			+ "    \"proofOfUpdates\": \"ROOF ONLY\",\r\n"
			+ "    \"securedCommunityBldg\": \"\",\r\n"
			+ "    \"sprinklerSystem\": \"NONE\",\r\n"
			+ "    \"openFoundation\": false,\r\n"
			+ "    \"hardiplankSiding\": false,\r\n"
			+ "    \"military\": true\r\n"
			+ "  },\r\n"
			+ "  \"windMitigation\": {\r\n"
			+ "    \"openingProtection\": \"NONE\",\r\n"
			+ "    \"roofCover\": \"FBC EQUIVALENT\",\r\n"
			+ "    \"roofDeck\": \"\",\r\n"
			+ "    \"roofDeckAttachment\": \"\",\r\n"
			+ "    \"roofShape\": \"GABLE\",\r\n"
			+ "    \"roofToWallAttachment\": \"\",\r\n"
			+ "    \"secondaryWaterResistance\": false\r\n"
			+ "  },\r\n"
			+ "  \"effectiveDate\": \"2022-02-01\",\r\n"
			+ "   \"dataReports\": {\r\n"
			+ "  	\"runInsuranceScore\": false\r\n"
			+ "  }	\r\n"
			+ "} ,\r\n"
			+ "  \"requestId\": \"8720-88776\",\r\n"
			+ "  \"responseDetail\": true\r\n"
			+ "}";
	
	RestAssured.baseURI=APIConstants.BASE_URI;
	
	RestAssured.given().auth().preemptive().
	basic(APIGlobalVariables.harvUsername, APIGlobalVariables.harvPassword).
	body(payload4)
	.contentType(ContentType.JSON).post().prettyPeek().then().
	assertThat().statusCode(200);
	
	System.out.println("All scenarios have passed for US-6287");
}


}
